apiVersion: v1
kind: ConfigMap
metadata:
  namespace: svc
  name: php-conf
  labels:
    app: php
    tier: backend
data:
  php-fpm.conf: |-
    [global]
    daemonize = no
    listen = 9000
    pid = run/php-fpm.pid
    
    process.priority = -19
    rlimit_files = 131072
    rlimit_core = unlimited
    security.limit_extensions = .php
    clear_env = yes
    
    ; https://github.com/docker-library/php/pull/725#issuecomment-443540114
    log_limit = 8192
    access.log = /proc/self/fd/2
    error_log = /proc/self/fd/2
    
    catch_workers_output = yes
    decorate_workers_output = no
    
    env[PATH] = /usr/local/bin
    
    php_flag[display_errors] = off
    
    include=etc/php-fpm.d/*.conf
immutable: false
