apiVersion: v1
kind: ConfigMap
metadata:
  namespace: svc
  name: php-fpm
  labels:
    app: php
    tier: backend
data:
  00-php.ini: |-
    [PHP]
    max_execution_time = 30
    memory_limit = 256M
  10-opcache.ini: |-
    zend_extension=opcache.so

    opcache.enable = 1
    opcache.memory_consumption = 128
    opcache.max_accelerated_files = 5000
    opcache.revalidate_freq = 0
    opcache.validate_timestamps = 0
  20-apcu.ini: |-
    extension = apcu.so

    [apcu]
    apc.enabled = 1
  20-gd.ini: |-
    extension = gd.so
  20-igbinary.ini: |-
    extension = igbinary.so

    igbinary.compact_strings = On
  20-intl.ini: |-
    extension = sodium.so
  20-pdo_mysql.ini: |-
    extension = pdo_mysql.so
  20-redis.ini: |-
    extension = redis.so
  25-apcu_bc.ini: |-
    '# extension = apc.so'
  www.conf: |-
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000

    pm = static
    pm.max_children = 10
    pm.max_requests = 500
immutable: false
