apiVersion: v1
kind: ConfigMap
metadata:
  namespace: svc
  name: php
  labels:
    app: php
    tier: backend
data:
  opcache.ini: |-
    zend_extension = opcache.so
    opcache.enable = 1
    opcache.memory_consumption = 128
    opcache.max_accelerated_files = 5000
    opcache.revalidate_freq = 0
    opcache.validate_timestamps = 0
  www.conf: |-
    [www]
    user = www-data
    group = www-data
    listen = 127.0.0.1:9000
    
    pm = static
    pm.max_children = 10
    pm.max_requests = 500
immutable: false
