---
apiVersion: v1
kind: Service
metadata:
  namespace: svc
  name: php-fpm
  labels:
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: php
    tier: backend
  ports:
  - name: php-fpm
    port: 9000
    protocol: TCP
